Vagrant.configure("2") do |config|
  config.vm.define "web_mail" do |web_mail|
    web_mail.vm.box = "ubuntu/bionic64"
    
    web_mail.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end
  
    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.network "forwarded_port", guest: 80, host: 8080
      
    web_mail.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install -y python3-pip apache2
      sudo cp /vagrant/index.html /var/www/html/index.html
      sudo chown www-data:www-data /var/www/html/index.html
      sudo chmod 644 /var/www/html/index.html
    SHELL
  end
end

