Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/jammy64"
    node1.vm.network "private_network", ip: "192.168.33.20"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    node1.vm.provision "ansible" do |ansible|
      ansible.playbook = "install_docker.yml"
      ansible.inventory_path = "inventory.ini"
    end
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/jammy64"
    node2.vm.network "private_network", ip: "192.168.33.21"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    node2.vm.provision "ansible" do |ansible|
      ansible.playbook = "install_docker.yml"  
      ansible.inventory_path = "inventory.ini"
    end
  end
end
